#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
A Password Generate Tool.

Example:

    $ python password.py
    Salt:
    Product:
    Password:
    Strategy:
    Password has pasted to your clipboard!
"""

from hashlib import md5
import click

def copy_to_board_for_mac_osx(string):
    import os
    os.system("echo '%s' | pbcopy" % string)

# Write your own password generated strategy.
def custom(salt, product, password):
    string = md5('%s%s%s' % (salt, product, password)).hexdigest()
    return string[:16].upper() + '+' + string[16:].lower()

def get_strategy(strategy):
    try:
        return {
        'normal': lambda salt, product, password: \
                md5('%s%s%s' % (salt, product, password)).hexdigest(),
        'upper': lambda salt, product, password: \
                md5('%s%s%s' % (salt, product, password)).hexdigest().upper(),
        'normal16': lambda salt, product, password: \
                md5('%s%s%s' % (salt, product, password)).hexdigest()[:16],
        'custom': custom
        }[strategy]
    except KeyError:
        raise Exception('Unknown strategy.')

@click.command()
@click.option('--salt', prompt=True, hide_input=True)
@click.option('--product', prompt=True, hide_input=True, default='')
@click.option('--password', prompt=True, hide_input=True)
@click.option('--strategy', prompt=True, hide_input=True)
def main(salt, product, password, strategy):
    product = product or ''
    generated = get_strategy(strategy)(salt, product, password)
    copy_to_board_for_mac_osx(generated)
    print('Password has pasted to your clipboard!')

if __name__ == '__main__':
    main()
